# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: portal
      POSTGRES_PASSWORD: schoolportal.project
      POSTGRES_DB: dbportal
    ports:
      - 5432:5432